version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
    ports:
      - 5432:5432
