// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeniorTeste.Infra.Data;

#nullable disable

namespace SeniorTeste.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeniorTeste.Domain.Entity.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Lat")
                        .HasColumnType("numeric")
                        .HasColumnName("Lat");

                    b.Property<decimal>("Lon")
                        .HasColumnType("numeric")
                        .HasColumnName("Lon");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.HasKey("Id")
                        .HasName("PK_IdCidade");

                    b.ToTable("Cidade", (string)null);
                });

            modelBuilder.Entity("SeniorTeste.Domain.Entity.Clima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("CidadeId");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataColeta");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric")
                        .HasColumnName("Temperatura");

                    b.HasKey("Id")
                        .HasName("PK_IdClima");

                    b.HasIndex("CidadeId");

                    b.ToTable("Clima", (string)null);
                });

            modelBuilder.Entity("SeniorTeste.Domain.Entity.Clima", b =>
                {
                    b.HasOne("SeniorTeste.Domain.Entity.Cidade", "Cidade")
                        .WithMany("Climas")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("SeniorTeste.Domain.Entity.Cidade", b =>
                {
                    b.Navigation("Climas");
                });
#pragma warning restore 612, 618
        }
    }
}
